### PR TITLE
fix: rename "Not Set" to "All" in stakeholders tool

### LINKED ISSUE #723: Stakeholders: Change "Not set" in filters to "All"
'Not Set' may be a little confusing – we use it elsewhere to mean show only records with null/empty values in this field.

Make the default "All" instead

_Originally posted by @nmcharlton in https://github.com/Greenstand/treetracker-admin-client/pull/340#discussion_r889707958_

### PR DESCRIPTION
**Pull request by tranquanghuy0801**
## Description

Rename "Not Set" to "All" in Stakeholders filter

**Issue(s) addressed**

- Resolves #723 

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [ ] Bug fix
- [x] Refactor

**Please check if the PR fulfils these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**

The current filter in Stakeholders uses `Not Set`, which is confusing to user in this tool

**What is the new behavior?**

Rename `Not Set` to `All`

## Breaking change

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

File: src/components/Stakeholders/Filter.js [hunk 1]
```diff
@@ -120,14 +120,14 @@ function StakeholderFilter() {
   const defaultOrgList = [
     {
       id: ORGANIZATION_NOT_SET,
```
Comment (nmcharlton) [inline src/components/Stakeholders/Filter.js:122]: We should change this const name to `ALL_ORGANIZATIONS` for consistency

**Review by nmcharlton — CHANGES_REQUESTED** [review]

File: src/components/Stakeholders/Filter.js (hunk 1 above)
Comment (nmcharlton) [reply src/components/Stakeholders/Filter.js:123]: I meant rename `ORGANIZATION_NOT_SET` (in `FilterStakeholder`) to `ALL_ORGANIZATIONS` everywhere it's used.

**Review by nmcharlton — APPROVED** [review]
