### PR TITLE
fix: add uuid to capture detail dialog and top filter

### LINKED ISSUE #110: Add UUID to Verify filter and Capture Detail
It should be possible to filter on a capture's UUID (`uuid` property).
Initially, this should be in the Verify tool, but #51 will align the Verify and Captures filters.
For consistency, the UUID should also be visible in the Capture Detail dialog (as a copyable item).

Currently there is no way to pull up a particular capture in the Admin Panel based on information in an image's file name (`TimeStamp-LatLong-UUID-OrigImageName.jpg`).
Date can be used, but this may pull up thousands of images.

### PR DESCRIPTION
**Pull request by tranquanghuy0801**
Resolves #110

### CODE REVIEW

**Review by nmcharlton — APPROVED** [review]

File: src/components/FilterTop.js [hunk 1]
```diff
@@ -164,6 +167,14 @@ function Filter(props) {
         <form onSubmit={handleSubmit}>
           <Grid container wrap="nowrap" direction="row">
             <Grid item className={classes.inputContainer}>
+              <TextField
```
Comment (nmcharlton) [inline src/components/FilterTop.js:170]: I'm not sure this field should go at the beginning of the filters.
Maybe after Capture ID would be better.

**Review by nmcharlton — CHANGES_REQUESTED** [review]

File: src/components/FilterTop.js (hunk 1 above)
Comment (tranquanghuy0801) [reply src/components/FilterTop.js]: @nmcharlton , I have updated as you requested

**Review by nmcharlton — APPROVED** [review]
