### PR TITLE
fix: date selection in filters

### LINKED ISSUE #94: Filter date selection: Cannot move forward
The forward button on the date selector used in filters on the _Verify_ and _Trees_ pages is permanently disabled, meaning you can't navigate to the next month if you go back.
Instead, you need to close the date selector and reopen it.

https://user-images.githubusercontent.com/5558838/119395353-4a8bf000-bccb-11eb-9ed6-e6043b200caf.mov

### PR DESCRIPTION
**Pull request by nmcharlton**
Resolves #94 

A `null` date passed into `KeyboardDatePicker` as `minDate` or `maxDate` causes the back and forward buttons respectively to be permanently disabled.

`1900-01-01` and `2100-01-01` are the default values for these properties (see https://material-ui-pickers.dev/api/DatePicker).

### CODE REVIEW

File: src/components/Filter.js [hunk 1]
```diff
@@ -285,7 +285,7 @@ function Filter(props) {
             value={dateStart}
             onChange={handleDateStartChange}
             format={getDateFormatLocale(true)}
-            maxDate={dateEnd}
+            maxDate={dateEnd || Date('2100-01-01')}
```
Comment (gwynndp) [inline src/components/Filter.js:288]: Perhaps we could add these default values to the state on line 58-59 so we can keep the initial state and it's defaults in one place?

File: src/components/FilterTop.js [hunk 2]
```diff
@@ -230,7 +230,7 @@ function Filter(props) {
                   format={getDateFormatLocale(true)}
                   value={dateStart}
                   onChange={handleDateStartChange}
-                  maxDate={dateEnd}
+                  maxDate={dateEnd || Date('2100-01-01')}
```
Comment (gwynndp) [inline src/components/FilterTop.js:233]: Same as with Filter.js we can set defaults on lines 72-73 so they are set from the start.

File: src/components/Filter.js (hunk 1 above)
Comment (nmcharlton) [reply src/components/Filter.js:288]: If I've understood your suggestion correctly, that doesn't have quite the desired result.
We want to keep the actual `dateStart` and `dateEnd` unset so that no value is selected in the input.
It's only the `minDate` and `maxDate` props that we need to set.

Comment (gwynndp) [reply src/components/Filter.js:288]: Ah, I misunderstood!  Ok, that solution works.  What do you think about adding comments to explain why the dates are there? or to create variables maxDateDefault and minDateDefault?  I'm concerned with someone changing or deleting the defaults in a refactor.
This would be a good thing to have a test for...

Comment (nmcharlton) [reply src/components/Filter.js:288]: That's a good shout, thanks. I'll make it a bit more explicit and add a test or two.

**Comment by dadiorchen** [comment]
@nikolamilijevic1 what's your opinion in terms of the usage of the cypress unit test, is it okay? Or there still are some barriers using it.

**Comment by nmcharlton** [comment]
The "fix" doesn't work quite as it should; needs a little more work 🤔

**Comment by nmcharlton** [comment]
Modified behaviour to not allow date selection after _today_ (since all data in the platform is historic), but to allow arbitrary start and end date selection in the past if the other value has not been set.
