### PR TITLE
fix: remove email and phone number from edit grower dialog

### LINKED ISSUE #239: Bug: When planter profiles get edited through the admin panel it breaks the field schema ingestion
I have just come across a case where an admin panel user changed the email address of a planter which resulted in the App data to get stuck in the "bulk_tree_upload" since there was no match of the identifier. Another case where i had edited multiple planter entries to match the telephone number resulted in the same issue.

### PR DESCRIPTION
**Pull request by rishad190**
## Description

_[Add a description of the changes]_

**Issue(s) addressed**

- Resolves #239 

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [x] Bug fix
- [ ] Refactor

**Please check if the PR fulfils these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**After fix**

### CODE REVIEW

File: src/components/EditGrower.js [hunk 1]
```diff
@@ -158,21 +158,25 @@ const EditGrower = (props) => {
...
-                  InputLabelProps={{
-                    shrink: true,
-                  }}
-                  onChange={(e) => {
-                    handleChange(input.attr, e.target.value);
-                  }}
-                  value={getValue(input.attr)}
-                />
+                <>
+                  {!(input.type === 'email') && !(input.type === 'tel') && (
```
Comment (nmcharlton) [inline src/components/EditGrower.js:162]: Rather than conditionally omitting inputs, it would be best to remove these items from the `inputs` array altogether. These values are not used anywhere else.

**Review by nmcharlton — CHANGES_REQUESTED** [review]
Thanks for picking this up, @rishad190!

File: src/components/EditGrower.js (hunk 1 above)
Comment (rishad190) [reply src/components/EditGrower.js]: @nmcharlton done . Look into this solution.
