### PR TITLE
fix: add trim method for typed entries in all filters #871

### LINKED ISSUE #871: Trim spaces from typed entries in all filters
Extra spaces cause values not to be matched.

### PR DESCRIPTION
**Pull request by henriquemoreiraa**
## Description

Trim method added for typed entries in all filters.

**Issue(s) addressed**

- Resolves #871 

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [x] Bug fix
- [ ] Refactor

**Please check if the PR fulfils these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**
If there are spaces at the beginning or at the end of the typed filter, the values cannot be matched.

**What is the new behavior?**
Values can be matched, whether they have spaces or not.

## Breaking change

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

File: src/components/common/CustomTableFilter/CustomTableFilter.js [hunk 1]
```diff
@@ -76,13 +76,17 @@ function CustomTableFilter(props) {
...
+      grower: localFilter.grower.trim(),
+      phone: localFilter.phone.trim(),
     };
 
     if (filtersToSubmit.organization_id === ALL_ORGANIZATIONS) {
       const modifiedFiltersToSubmit = {
         ...filtersToSubmit,
         organization_id: '',
         sub_organization: '',
+        grower: localFilter.grower.trim(),
```
Comment (nmcharlton) [inline src/components/common/CustomTableFilter/CustomTableFilter.js:88]: You don't need to add these fields again. They're already in `filtersToSubmit`.

**Review by nmcharlton — CHANGES_REQUESTED** [review]

**Review by nmcharlton — APPROVED** [review]
Thanks @henriquemoreiraa!
