### PR TITLE
fix: add REACT_APP_WEBMAP_DOMAIN in the link

### LINKED ISSUE #727: The map name needs to be prefixed with `REACT_APP_WEBMAP_DOMAIN` in the link.
The map name needs to be prefixed with `REACT_APP_WEBMAP_DOMAIN` in the link.

_Originally posted by @nmcharlton in https://github.com/Greenstand/treetracker-admin-client/pull/340#discussion_r911379941_

### PR DESCRIPTION
**Pull request by sunfallcitadel**
## Description

Add REACT_APP_WEBMAP_DOMAIN  to the map link if the stakeholder detail data has map.

**Issue(s) addressed**

- Resolves #727 

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [X] Bug fix
- [ ] Refactor

**Please check if the PR fulfils these requirements**

- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: src/components/Stakeholders/StakeholderDetail/Header.js [hunk 1]
```diff
@@ -412,11 +413,18 @@ export default function StakeholderDialogHeader({
...
-                <Typography className={classes.fields}>
-                  <Link href={details?.map} target="_blank">
-                    {details?.map}
-                  </Link>
-                </Typography>
+                <>
+                  {details?.map && (
+                    <Typography className={classes.fields}>
+                      <Link
+                        href={`${process.env.REACT_APP_WEBMAP_DOMAIN}/${details?.map}`}
```
Comment (nmcharlton) [inline src/components/Stakeholders/StakeholderDetail/Header.js:420]: No need for the `?` after `details` – we can't get here if `details` is `null`.

File: src/components/Stakeholders/StakeholderDetail/Header.js [hunk 2]
```diff
@@ -412,11 +413,18 @@ export default function StakeholderDialogHeader({
...
+                        target="_blank"
+                      >
+                        {details?.map}
```
Comment (nmcharlton) [inline src/components/Stakeholders/StakeholderDetail/Header.js:423]: No need for the ? after details – we can't get here if details is null.

**Review by nmcharlton — APPROVED** [review]

File: src/components/Stakeholders/StakeholderDetail/Header.js [hunk 3]
```diff
@@ -412,11 +413,18 @@ export default function StakeholderDialogHeader({
...
               ) : (
-                <Typography className={classes.fields}>
-                  <Link href={details?.map} target="_blank">
-                    {details?.map}
-                  </Link>
-                </Typography>
+                <>
+                  {details?.map && (
+                    <Typography className={classes.fields}>
+                      <Link
```
Comment (nmcharlton) [inline src/components/Stakeholders/StakeholderDetail/Header.js:419]: It would be a good idea to move the `<Link>` outside of the `<Typography>` element while making this change. It probably doesn't matter so much here, but it can cause odd behaviour if the link is too far in.

Comment (fengtao321) [reply src/components/Stakeholders/StakeholderDetail/Header.js]: Thanks for the comment, I removed the Typography, and use the props on Typography on Link. Double checked the styles on browser.
image
