### PR TITLE
fix: show warning for unsaved changes in editing stakeholder

### LINKED ISSUE #732: If `isEditing` is true, show a warning before closing to prevent users losing unsaved changes.
If `isEditing` is true, show a warning before closing to prevent users losing unsaved changes.

_Originally posted by @nmcharlton in https://github.com/Greenstand/treetracker-admin-client/pull/340#discussion_r911409708_

### PR DESCRIPTION
**Pull request by tranquanghuy0801**
## Description

Editing Stakeholder detail - Show warning for unsaved changes

**Issue(s) addressed**

- Resolves #732 

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [x] Bug fix
- [ ] Refactor

**Please check if the PR fulfils these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**

Close the dialog when editing the stakeholder will clear all the changes

**What is the new behavior?**

Show a warning dialog when editing the stakeholder to alert the users that they have unsaved changes

## Breaking change

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

File: src/components/Stakeholders/StakeholderDetail/StakeholderDetail.js [hunk 1]
```diff
@@ -69,18 +78,64 @@ export default function StakeholderDetail({ row, columns, child }) {
...
+    }
+  
+    return (
+      showAlert && <Dialog
+          open={showAlert}
+          onClose={() => setShowAlert(false)}
+        >
+          <DialogContent>
+            <Typography variant="h6" className={classes.alertText}>
+              You have unsaved changes. Close the dialog will clear all the changes.
```
Comment (nmcharlton) [inline src/components/Stakeholders/StakeholderDetail/StakeholderDetail.js:112]: Let's make things easier for the user:
> Save changes?
> Cancel | Discard | Save

**Review by nmcharlton — CHANGES_REQUESTED** [review]

**Comment by tranquanghuy0801** [comment]
@nmcharlton sorry for that. I have attached a video screenshot to demo my work. Hope this helps.

https://user-images.githubusercontent.com/29462498/183887468-802871ae-fe29-4df1-b4ab-7a55f954f242.mov

**Review by nmcharlton — APPROVED** [review]
Looks great, thanks @tranquanghuy0801!

File: src/components/Stakeholders/StakeholderDetail/StakeholderDetail.js [hunk 2]
```diff
@@ -126,7 +174,12 @@ export default function StakeholderDetail({ row, columns, child }) {
         </IconButton>
 
         <DialogContent className={`${classes.my} ${classes.noScroll}`}>
-          <StakeholderDialogHeader data={rowData} />
+          <StakeholderDialogHeader
+            data={rowData}
+            isEditing={isEditing}
+            setIsEditing={setIsEditing}
+            forceSave={!open && !isEditing && !showAlert}
```
Comment (nmcharlton) [inline src/components/Stakeholders/StakeholderDetail/StakeholderDetail.js:181]: I'm not sure I understand the logic here. Surely `forceSave` is true whenever the dialog is closed, so we trigger `handleSave()` far more than we should.

**Review by nmcharlton — CHANGES_REQUESTED** [review]

File: src/components/Stakeholders/StakeholderDetail/Header.js [hunk 3]
```diff
@@ -149,6 +153,10 @@ export default function StakeholderDialogHeader({ data }) {
 
   const defaultTypeList = ['Organization', 'Person'];
 
+  useEffect(() => {
+    if (forceSave) handleSave();
+  });
```
Comment (nmcharlton) [inline src/components/Stakeholders/StakeholderDetail/Header.js:158]: To prevent unnecessary calls, pass `[forceSave]` as a second parameter to `useEffect()`.

Comment (tranquanghuy0801) [reply src/components/Stakeholders/StakeholderDetail/Header.js]: I have updated this one

File: src/components/Stakeholders/StakeholderDetail/StakeholderDetail.js (hunk 2 above)
Comment (tranquanghuy0801) [reply src/components/Stakeholders/StakeholderDetail/StakeholderDetail.js]: Thanks for pointing this out. I thought doing this way would me from creating another state variable, turning out it was not effective. I created a variable `forceSave` instead.

**Review by nmcharlton — APPROVED** [review]
