### PR TITLE
Reporting fix

### LINKED ISSUE #1100: Specific reporting cards display empty entries
Some of the reporting cards show empty entries, as seen in the images:

image
image

### LINKED ISSUE #1102: Grower Gender Counts reporting card displays entry incorrectly
The reporting card, when the detailed modal is opened by clicking See More and is closed, the entry disappears (empty value). 
Recording 2023-07-03 at 22 59 20

### PR DESCRIPTION
**Pull request by pranavkparti**
## Description
The Growers, Captures, Unverified Captures, and Average Captures per Grower reporting cards show  'No organization' instead of an empty entry. 

**Issue(s) addressed**
- Resolves #1100 
- Resolves #1102 

**What kind of change(s) does this PR introduce?**
- [] Enhancement
- [X] Bug fix
- [ ] Refactor

**Please check if the PR fulfils these requirements**
- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**
 Some of the reporting cards show empty entries instead of some non-null value.

**What is the new behavior?**
image
image
The reporting cards show 'No organization' instead of an empty entry.

## Breaking change

**Does this PR introduce a breaking change?**
No.

## Other useful information
None.

### CODE REVIEW

File: src/components/reportingCards/ReportingCard1.js [hunk 1]
```diff
@@ -15,6 +15,25 @@ export default function ReportingCard1(props) {
     rows
   );
 
+  const formatData = (data) => {
```
Comment (nmcharlton) [inline src/components/reportingCards/ReportingCard1.js:18]: Rather than duplicating this function across reporting cards, I'd suggest creating a shared utility function that replaces blank entries with "No organization" and giving it a name that indicates that modification.

To be more general, it could take the string you want to use in place of blank entries as an input.

**Review by nmcharlton — CHANGES_REQUESTED** [review]

File: src/components/reportingCards/ReportingCard1.js (hunk 1 above)
Comment (pranavkparti) [reply src/components/reportingCards/ReportingCard1.js:18]: That was what I originally went with, but there could be other reporting cards later as well. There is a card with gender, and species. But I see you point. We can change the reporting card itself to accept a default value that is displayed if the entry is empty.

Comment (pranavkparti) [reply src/components/reportingCards/ReportingCard1.js]: @nmcharlton For now I've just shifted the formatData function to utilities. It would be better to refactor the reporting cards in a separate issue.
