### PR TITLE
fix: change web map links

### LINKED ISSUE #972: Urgent: all web map links need to link to the new beta webmap URL in the new format
All map links can now be replaced with 

https://beta-map.treetracker.org/planters/8432/trees/3975488
https://map.treetracker.org/?userid=8446 = https://beta-map.treetracker.org/planters/8446
https://map.treetracker.org/?treeid=4000292 = https://beta-map.treetracker.org/trees/4000292

The old map has too many issues is incredibly slow.

### PR DESCRIPTION
**Pull request by henriquemoreiraa**
## Description

Change links for the web map in the verify, capture and grower tools

**Issue(s) addressed**

- Resolves #972 

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [ ] Bug fix
- [x] Refactor

**Please check if the PR fulfils these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**
The link for the web map was https://dev.treetracker.org/?userid=5846

**What is the new behavior?**
Now the current link is https://beta-map.treetracker.org/planters/5846

## Breaking change

**Does this PR introduce a breaking change?**

### CODE REVIEW

File: src/components/CaptureDetailDialog.js [hunk 1]
```diff
@@ -188,7 +188,7 @@ function CaptureDetailDialog(props) {
             <Grid item>
               <Box m={4}>
                 <Typography color="primary" variant="h6">
-                  Capture <LinkToWebmap value={capture} type="tree" />
+                  Capture <LinkToWebmap value={capture} type="trees" />
```
Comment (nmcharlton) [inline src/components/CaptureDetailDialog.js:191]: Do you think we could define a shared `const` object with the two possible values for `type`?
That would mean we only need to change the string literal values in one place if the web map path changes, and minimised the risk of a bug through a typo.

File: .env.development [hunk 2]
```diff
@@ -1,4 +1,4 @@
-REACT_APP_WEBMAP_DOMAIN=http://dev.treetracker.org
+REACT_APP_WEBMAP_DOMAIN=https://beta-map.treetracker.org
```
Comment (nmcharlton) [inline .env.development:1]: It's the `.env.staging` and `.env.production` domains that should point at this URL.
@dadiorchen Is there a `dev` and `test` URL available for the beta web map?

File: src/components/GrowerDetail.js [hunk 3]
```diff
@@ -414,7 +414,13 @@ const GrowerDetail = ({ open, growerId, onClose }) => {
                   {grower.firstName} {grower.lastName}
                 </Typography>
                 <Typography variant="body2">
-                  ID: <LinkToWebmap value={grower.id} type="user" />
+                  ID:{' '}
+                  <LinkToWebmap
+                    value={
+                      grower.reference_id ? grower.reference_id : grower.id
```
Comment (nmcharlton) [inline src/components/GrowerDetail.js:420]: This can be shortened to `value={ grower.reference_id || grower.id` }`

File: src/components/Growers/Grower.js [hunk 4]
```diff
@@ -52,7 +52,11 @@ export const Grower = ({ grower, growerClick }) => {
               {grower.firstName} {grower.lastName}
             </Typography>
             <Typography>
-              ID: <LinkToWebmap value={grower.id} type="user" />
+              ID:{' '}
+              <LinkToWebmap
+                value={grower.reference_id ? grower.reference_id : grower.id}
```
Comment (nmcharlton) [inline src/components/Growers/Grower.js:57]: This can be shortened to `value={ grower.reference_id || grower.id` }`

**Review by nmcharlton — CHANGES_REQUESTED** [review]

**Comment by nmcharlton** [comment]
Sorry @henriquemoreiraa, it looks like there is no dev deployment of the new web map, so we'll have to use the same URL for all environments for now. Can you add this to `.env.development` (again) and `.env.test`?
```
REACT_APP_WEBMAP_DOMAIN=https://beta-map.treetracker.org
```

**Review by nmcharlton — APPROVED** [review]
