### PR TITLE
Fix filtering by organizations using legacy auth and queries to microservices

### LINKED ISSUE #977: Only show and allow filtering by orgs user is permitted to see (using legacy api for auth and new apis for queries)

### PR DESCRIPTION
**Pull request by gwynndp**
## Description

- update SelectOrg to use uuid
- add way to get the org uuid and list of child org uuids from AppContext after login
- update tests to work
- refactor to make query string to use whereNulls, whereNotNulls, whereIns arrays
- adjust filters to work with the new query arrays (tags, organizations, species isn't in filters currently so not tested)

**Issue(s) addressed**

- Resolves #977 
- Relates to api update (https://github.com/Greenstand/treetracker-query-api/pull/268)

**What kind of change(s) does this PR introduce?**

- [x] Enhancement
- [x] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: src/context/VerifyContext.js [hunk 1]
```diff
@@ -138,6 +144,21 @@ export function VerifyProvider(props) {
     //set loading status
     setIsLoading(true);
 
+    if (!filter.organizationId && orgId === null) {
```
Comment (nmcharlton) [inline src/context/VerifyContext.js:147]: This looks like duplicate code (from `GrowerContext`). Given the complexity of the logic, it would definitely be worth making a common function that does this.

File: src/models/Filter.js [hunk 2]
```diff
@@ -231,22 +227,18 @@ export default class Filter {
...
     }
 
-    if (this.tokenId && this.tokenId !== 'All') {
-      numFilters += 1;
-    }
-
-    if (this.status) {
-      numFilters += 1;
-    }
+    // if (this.tokenId && this.tokenId !== 'All') {
```
Comment (nmcharlton) [inline src/models/Filter.js:239]: What's the reason for commenting this out?

**Review by nmcharlton — CHANGES_REQUESTED** [review]

File: src/models/Filter.js (hunk 2 above)
Comment (gwynndp) [reply src/models/Filter.js:239]: Mental blip.  I was only considering Verify where we aren't currently filtering by token.

File: src/common/utils.js [hunk 3]
```diff
@@ -10,6 +12,34 @@ export const getVerificationStatus = (active, approved) => {
   }
 };
 
+export const setOrganizationFilter = (filter, orgId, orgList) => {
+  // if orgId has a value filter by orgId and sub-orgs, don't include null org ids
+  if (filter.organization_id === ALL_ORGANIZATIONS && orgId) {
```
Comment (nmcharlton) [inline src/common/utils.js:17]: My understanding from the `if` clauses in this function is that only one can be true.
To make that a bit clearer, I'd suggest a chain of `if ... else if ...`

**Review by nmcharlton — APPROVED** [review]

**Review by Siddhant-K-code — COMMENTED** [review]
Possibly unrelated file changes are failing tests. See [here](https://github.com/Greenstand/treetracker-admin-client/actions/runs/3977030788/jobs/6817874725#step:9:2994) 👀
 
image

**Comment by nmcharlton** [comment]
@Siddhant-K-code That's not the test that's failing; it's this one:
```
 FAIL  src/components/tests/verify.test.js (5.315 s)
  Verify
    with default values
      ✓ renders number of applied filters (1725 ms)
      ✕ renders capture details (1241 ms)
      ✓ renders grower details (659 ms)
      ○ skipped renders filter top
      ○ skipped renders captures gallery
      ○ skipped renders edit planter

  ● Verify › with default values › renders capture details

    TypeError: Cannot read properties of undefined (reading 'then')

      70 |
      71 |     try {
    > 72 |       api.getCaptureTags([captureId]).then((tags) => {
         |       ^
      73 |         console.log('All tags: ', tags);
      74 |         setState({ ...state, tags: tags[0] });
      75 |       });
```

File: src/common/utils.js (hunk 3 above)
Comment (gwynndp) [reply src/common/utils.js:17]: It's tricky to come up with variable names.  The filter.organization_id is the filter selected and the "orgId" is the uuid of the logged in user's organization.  

I'll write a comment, but I'm open to better suggestions.

Comment (nmcharlton) [reply src/common/utils.js:18]: How about `userOrgId`?

File: src/api/apiUtils.js [hunk 4]
```diff
@@ -39,3 +39,51 @@ export function getOrganizationId() {
 export function getOrganizationUUID() {
   return session.user?.policy?.organization?.uuid || null;
 }
+
+export const makeQueryString = (filterObj) => {
+  // log.debug('makeQueryString 1 ----->', filterObj);
+  const arr = [];
```
Comment (nmcharlton) [inline src/api/apiUtils.js:45]: None of `arr`, `whereNulls`, `whereNotNulls` or `whereIns` should be declared `const`.
They're all potentially modified after declaration.

**Review by nmcharlton — CHANGES_REQUESTED** [review]
Just a minor comment on the use of `const`. Otherwise, looks great!

File: src/api/apiUtils.js [hunk 5]
```diff
@@ -42,10 +42,10 @@ export function getOrganizationUUID() {
 
 export const makeQueryString = (filterObj) => {
   // log.debug('makeQueryString 1 ----->', filterObj);
-  const arr = [];
```
Comment (nmcharlton) [inline src/api/apiUtils.js]: Sorry @gwynndp, I'm being an idiot. You were right to make these `const`.
I'm still getting up to speed with all this modern JS stuff 🤣 

I'll change it back.

**Review by nmcharlton — APPROVED** [review]
