### PR TITLE
fix: capture - incorrectly formed csv file #851

### LINKED ISSUE #851: Capture tool. Download not producing a valid csv file when selecting individual columns
See screenshot. The scv file only contains -- Ôªø -- when opened in Excel
Screenshot 2022-09-29 at 10 12 14

### PR DESCRIPTION
**Pull request by Vlad-Pischaeff**
## Description

Download producing a valid csv file when selecting individual columns

**Issue(s) addressed**

- Resolves #851

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [x] Bug fix
- [ ] Refactor

**Please check if the PR fulfils these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**
Download not producing a valid csv file when selecting individual columns

**What is the new behavior?**
Download producing a valid csv file when selecting individual columns

## Breaking change

**Does this PR introduce a breaking change?**
No

## Other useful information
imageUrl field additionally fixed, ReactDOM warning fixed

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import './init';
 import React from 'react';
-import ReactDOM from 'react-dom';
+import ReactDOM from 'react-dom/client';
```
Comment (nmcharlton) [inline src/index.js:3]: We can remove this. I've not set the `react` and `react-dom` versions to `18` in `package.json`.

**Review by nmcharlton — CHANGES_REQUESTED** [review]

**Review by nmcharlton — APPROVED** [review]
