### PR TITLE
fix: forget route when a user logs out explicit

### LINKED ISSUE #624: Forget route when a user logs out explicitly
Some of our users have more than one Admin Panel account (e.g., to support multiple organizations).
When a user logs out of one account (from the Account page) and logs in with another, they are redirected to the last page they were on (Account) which seems like odd behaviour.

When they log out explicitly by clicking _Log Out_, then log back in, we should redirect them to the home page.

Note that the redirection to the last page is desired behaviour on an _implicit_ logout (e.g., token expiry) to minimise disruption. This should be retained.

### PR DESCRIPTION
**Pull request by rishad190**
## Description

_[Add a description of the changes]_

**Issue(s) addressed**

- Resolves #624 

**What kind of change(s) does this PR introduce?**

- [x] Enhancement
- [ ] Bug fix
- [ ] Refactor

**Please check if the PR fulfils these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: src/components/Login.js [hunk 1]
```diff
@@ -66,8 +66,8 @@ const Login = (props) => {
 
   const history = useHistory();
   const location = useLocation();
-  const { from } = location.state || { from: { pathname: '/' } };
-
+  const { from } = { from: { pathname: '/' } };
+  console.log(location);
```
Comment (nmcharlton) [inline src/components/Login.js:70]: You can remove `console.log()` when development is complete so we don't pollute the console in production. If you need to keep logging in production, use `loglevel` instead.

File: src/components/Login.js [hunk 2]
```diff
@@ -66,8 +66,8 @@ const Login = (props) => {
 
   const history = useHistory();
   const location = useLocation();
-  const { from } = location.state || { from: { pathname: '/' } };
```
Comment (nmcharlton) [inline src/components/Login.js:69]: I can't test this at the moment, but it looks like this will cause us to _always_ forget the path. Instead, we should only forget it when a user _explicitly_ logs out via the Account page.

If they are redirected to the login page (e.g., because their session expired or they weren't logged in to begin with), the path they entered should be remembered.

**Review by nmcharlton — CHANGES_REQUESTED** [review]

**Comment by rishad190** [comment]
@nmcharlton now it's working fine. You can check now.

**Review by nmcharlton — APPROVED** [review]
Nice work 😄
