### PR TITLE
Messaging: update messages and sort inbox when new things added w/o refreshing

### LINKED ISSUE #469: Writing a new message reloads the page
Writing a new message reloads the entire page, and the message the user was viewing is no longer shown.

Writing a new message should just append to the message window for the thread being viewed.

### LINKED ISSUE #480: Show error to user when "catch error: HttpError: No author handle found in the specified organization"

### LINKED ISSUE #482: If an announce message title is duplicated, it does not show in the UI after send

### PR DESCRIPTION
**Pull request by gwynndp**
## Description

- changes throughout to keep up with api changes
- added client-side state updates so that the user can see their sent messages/announcements/surveys added immediately
- makes sure error message displays when no authors found for sending messages/announcements/surveys

**Issue(s) addressed**

- Resolves #469
- Resolves #480
- Resolves #482

**What kind of change(s) does this PR introduce?**

- [x] Enhancement
- [x] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: src/components/Messaging/AnnounceMessage.js [hunk 1]
```diff
@@ -109,8 +115,41 @@ const AnnounceMessageForm = ({ setToggleAnnounceMessage }) => {
...
+          setThreads((prev) => {
+            const updated = [
+              {
+                username: `${newAnnouncement.id}`,
+                messages: [newAnnouncement],
+                avatar: '',
+              },
+              ...prev,
+            ];
+            return updated;
```
Comment (TANguyen1893) [inline src/components/Messaging/AnnounceMessage.js:150]: Maybe you can simplify this and return directly the array instead of creating a variable and returning it.

File: src/components/Messaging/MessageBody.js [hunk 2]
```diff
@@ -370,61 +371,69 @@ const SenderInformation = ({
...
-            {type === 'survey' && (
-              <Typography>
-                <b>RESPONSES:</b> {responseCount}
+              <Typography align="left" color="primary">
+                <b>TO:</b>{' '}
+                {message?.bulk_message_recipients.length
+                  ? message?.bulk_message_recipients[0]?.recipient
+                  : message?.recipient_organization_id
+                  ? message?.recipient_organization_id
+                  : message?.recipient_region_id}
```
Comment (TANguyen1893) [inline src/components/Messaging/MessageBody.js:395]: Can this be extracted to a method? It's a bit confusing with all the conditions.

File: src/components/Messaging/MessageBody.js [hunk 3]
```diff
@@ -488,9 +497,41 @@ const MessageBody = ({ messages, messageRecipient, avatar }) => {
         const res = await postMessageSend(messagePayload);
         if (res.error) {
           setErrorMessage(res.message);
-          handleModalOpen();
         } else {
-          history.go(0);
+          const newMessage = {
+            parent_message_id: lastMessage.id ? lastMessage.id : null,
```
Comment (TANguyen1893) [inline src/components/Messaging/MessageBody.js:502]: Couldn't you just simplify it to `lastMessage.id`?

File: src/components/Messaging/Messaging.js [hunk 4]
```diff
@@ -140,17 +149,24 @@ const Messaging = () => {
...
             handleListItemClick={handleListItemClick}
           />
         </Grid>
         <Grid item className={body} xs={7} md={8}>
-          {messages.length ? (
+          {/* {console.log(
+            'selectedIndex currentThread --- ',
+            selectedIndex,
+            currentThread
+          )} */}
```
Comment (TANguyen1893) [inline src/components/Messaging/Messaging.js:162]: I think we can remove this

File: src/components/Messaging/Messaging.js [hunk 5]
```diff
@@ -140,17 +149,24 @@ const Messaging = () => {
...
+          {threads.length ? (
             <MessageBody
-              messages={messages[selectedIndex].messages}
-              messageRecipient={messages[selectedIndex].userName}
-              avatar={messages[selectedIndex].avatar}
+              messages={threads.length && threads[selectedIndex].messages}
+              messageRecipient={
+                threads.length && threads[selectedIndex].userName
+              }
+              avatar={threads.length && threads[selectedIndex].avatar}
```
Comment (TANguyen1893) [inline src/components/Messaging/Messaging.js:169]: I don't think the check for `threads.length` is needed since you already do this check on line 163.

File: src/components/Messaging/Survey.js [hunk 6]
```diff
@@ -158,8 +167,41 @@ const SurveyForm = ({ setToggleSurvey }) => {
...
+          setThreads((prev) => {
+            const updated = [
+              {
+                username: `${newSurvey.id}`,
+                messages: [newSurvey],
+                avatar: '',
+              },
+              ...prev,
+            ];
+            return updated;
```
Comment (TANguyen1893) [inline src/components/Messaging/Survey.js:202]: You can return directly the object instead of saving it in a variable and returning the variable

File: src/context/MessagingContext.js [hunk 7]
```diff
@@ -104,22 +88,38 @@ export const MessagingProvider = (props) => {
...
-      setAuthors(result);
+
+      log.debug('...load author avatars');
+      if (result.length) {
+        Promise.all(
+          result.map(async (author) => {
+            const { grower_accounts } = await api.getAuthorAvatar(
+              author.handle
+            );
+            // log.debug('grower_accounts', grower_accounts[0]?.image_url);
```
Comment (TANguyen1893) [inline src/context/MessagingContext.js:115]: We can remove unused logging

File: src/context/MessagingContext.js [hunk 8]
```diff
@@ -104,22 +88,38 @@ export const MessagingProvider = (props) => {
...
+            return { ...author, avatar: grower_accounts[0]?.image_url || '' };
+          })
+        ).then((data) => {
+          // log.debug('...update authors with avatars', data);
```
Comment (TANguyen1893) [inline src/context/MessagingContext.js:119]: Same thing above with unused logging

**Review by ZavenArra — APPROVED** [review]
Functional review looks good.  I'm going to merge this PR so contributions can continue.

File: src/components/Messaging/MessageBody.js (hunk 2 above)
Comment (ZavenArra) [reply src/components/Messaging/MessageBody.js:395]: referenced this in a new issue.

File: src/components/Messaging/MessageBody.js (hunk 3 above)
Comment (ZavenArra) [reply src/components/Messaging/MessageBody.js]: referenced to new issue so we can merge.

**Comment by gwynndp** [comment]
@TANguyen1893 Thank you for all your feedback!  I've implemented your changes in other PRs.
