### PR TITLE
fix: assorted improvements to capture matching UI

### LINKED ISSUE #361: Capture Matching: Grower name and photo not displayed
The grower name and photo come through from the API as `grower_username` and `grower_photo_url` respectively, but the client is looking for `planter_...`.
The client should be updated.

### LINKED ISSUE #362: Capture Matching: Display candidate match tree UUID

### LINKED ISSUE #363: Capture Matching: Show proximity and interval of candidate tree captures relative to current capture

### PR DESCRIPTION
**Pull request by nmcharlton**
## Description

This PR introduces several improvements to the Capture Matching tool:
1. Show date and proximity of candidate match captures
2. Display grower image and name
3. Tidy styling of various elements, including buttons and general spacing
4. Make unmatched capture image fully visible without scrolling
5. Relabel _Same / DIfferent Tree_ buttons as _Confirm Match_ and _Dismiss_ to make their actions clearer
6. Animate collapse of candidate match card
7. Remove unused filter placeholder chips

Screenshot 2022-02-05 at 21 37 36

https://user-images.githubusercontent.com/5558838/152700065-03078205-98a5-4e89-b41d-b2d07f111714.mov

**Issue(s) addressed**

- Resolves #361 
- Resolves #362 
- Resolves #363 

**What kind of change(s) does this PR introduce?**

- [x] Enhancement
- [x] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: src/components/CaptureMatching/CaptureImage.js [hunk 1]
```diff
@@ -128,30 +134,30 @@ function CaptureImage(props) {
...
+                    </Box>
                   </Box>
-                  {/* <UseLocation/> */}
                 </Box>
 
                 <Grower
-                  planter_photo_url={capture.planter_photo_url}
-                  planter_username={capture.planter_username}
-                  status={capture.status}
+                  grower_photo_url={capture.grower_photo_url}
```
Comment (nmcharlton) [inline src/components/CaptureMatching/CaptureImage.js:154]: Looks like I jumped the gun on this one.
The API is being changed to only include `grower_account_id` under Greenstand/treetracker-api#55.
I guess we'll need to look up the grower info instead.

Comment (gwynndp) [reply src/components/CaptureMatching/CaptureImage.js:154]: I think we should keep this until the API changes.

**Review by gwynndp — APPROVED** [review]

**Comment by gwynndp** [comment]
Looks much better!
