### PR TITLE
fix: display Full Capture Details in Verify and Captures pages

### LINKED ISSUE #220: Full capture details not loaded in Capture Detail dialog
When a user opens the Capture Detail dialog (by clicking the tree icon in the _Verify_ tool or a row in the _Captures_ tool), the Admin Panel should load the full capture details, including tags and species.

Screenshot 2021-11-29 at 19 36 16

**Captures**
In the _Captures_ tool, Species and Additional tags are missing.
The client appears to query the capture but not these additional details.
Screenshot 2021-11-29 at 19 48 50

**Verify**
In the _Verify_ tool, all of the "Other" tags are missing, as well as Species and token status.
The client does not query the capture at all.
Screenshot 2021-11-29 at 19 41 44

I can see a couple of things causing this:

- We're not wrapping these views with `CaptureDetailProvider` tags
- We don't return `capture` from `CaptureDetailContext::getCapture()` so it can't be passed to subsequent queries

### PR DESCRIPTION
**Pull request by tranquanghuy0801**
…Captures pages

## Description

This PR fixed the issue of not displaying full species and other tags in Capture Detail Dialog.

**Issue(s) addressed**

- Resolves #220 

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [x] Bug fix
- [ ] Refactor

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**

Not display the species tags in Captures page, and not display the species tags and the other tags in Verify page

**What is the new behavior?**

Both species and other tags are displayed fully in Verify and Captures pages.

## Breaking change

**Does this PR introduce a breaking change?**

No breaking change

### CODE REVIEW

File: src/components/CaptureDetailDialog.js [hunk 1]
```diff
@@ -85,7 +88,10 @@ function CaptureDetailDialog(props) {
 
   useEffect(() => {
     cdContext.getCaptureDetail(capture.id);
-
+    const filterSpecies = capture.speciesId ? speciesContext.speciesList.filter(spec => spec.id === capture.speciesId) : [];
```
Comment (nmcharlton) [inline src/components/CaptureDetailDialog.js:91]: Instead of `speciesList.filter()` here, use `speciesList.find()` with the same comparison function.
It will return the first match, or `null` if there are no matches.

File: src/api/treeTrackerApi.js [hunk 2]
```diff
@@ -113,9 +122,15 @@ export default {
       .catch(handleError);
   },
   getCaptureById(id) {
+    const lbFilter = {
+      order: [`${'asc'} ${'id'}`],
```
Comment (nmcharlton) [inline src/api/treeTrackerApi.js:126]: `order` doesn't make sense here. This query only returns one record.

**Review by nmcharlton — CHANGES_REQUESTED** [review]
This is good, but it doesn't address the whole problem.
In particular, we still don't see the capture tags (AKA treeTags).
See my comments in the issue for how to resolve that part:
> I can see a couple of things causing this:
>
> - We're not wrapping these views with `CaptureDetailProvider` tags
> - We don't return capture from `CaptureDetailContext::getCapture()` so it can't be passed to subsequent queries

File: src/api/treeTrackerApi.js [hunk 3]
```diff
@@ -1,6 +1,28 @@
 import { handleResponse, handleError, getOrganization } from './apiUtils';
 import { session } from '../models/auth';
 
+const FIELDS = {
```
Comment (nmcharlton) [inline src/api/treeTrackerApi.js:4]: I'd suggest renaming this `CAPTURE_FIELDS` to make its use clear

File: src/api/treeTrackerApi.js (hunk 2 above)
Comment (nmcharlton) [reply src/api/treeTrackerApi.js:126]: In fact, this endpoint ignores the param string, so the filter is redundant here. The whole record is always returned for a query by ID.

**Review by nmcharlton — APPROVED** [review]
@tranquanghuy0801 I hope you don't mind, I've made the changes myself so we can get the fix into the next build. Thanks for your work on this!

**Comment by tranquanghuy0801** [comment]
> @tranquanghuy0801 I hope you don't mind, I've made the changes myself so we can get the fix into the next build. Thanks for your work on this!

@nmcharlton That's alright. I totally understand. Happy to have a new release.
